version: '3'
services:
  postgres:
    image: "postgres:10"
    env_file: .env
    volumes:
      - ./voltrader_data:/var/lib/postgresql/data
    networks:
      - voltrader
  voltrader:
    image: "sheehan95/voltrader"
    env_file: .env
    networks:
      - voltrader
    depends_on:
      - postgres
    command: ["iex", "-S", "mix"]